export const LOAD_LOOTSPECS_SUCCESS = 'LOAD_LOOTSPECS_SUCCESS';
export const CREATE_LOOTSPECS_SUCCESS = 'CREATE_LOOTSPECS_SUCCESS';
export const SAVE_LOOTSPECS_SUCCESS = 'SAVE_LOOTSPECS_SUCCESS';
export const LOAD_GAMES_SUCCESS = 'LOAD_GAMES_SUCCESS';
export const CREATE_GAMES_SUCCESS = 'CREATE_GAMES_SUCCESS';


export const LOAD_LOOTS_SUCCESS = 'LOAD_LOOTS_SUCCESS';
export const CREATE_LOOTS_SUCCESS = 'CREATE_LOOTS_SUCCESS';
export const SAVE_LOOTS_SUCCESS = 'SAVE_LOOTS_SUCCESS';


